site_name: PARS - HEAD Lab
repo_url: https://github.com/HEADLabIC/PARS.git
edit_uri: tree/main/docs/

nav:
  - Home: index.md
  - Installation: 01_Installation.md
  - Usage: 02_Usage.md
  # - Outputs: outputs.md
  # - How PARS works:
  #     - Overview: workflows.md
  #     - Image processing: image-processing.md
  #     - Mesh generation: mesh-generation.md
  # - Evaluation: evaluation.md
  # - Troubleshooting: troubleshooting.md
  # - Citation: citation.md

theme:
  name: material
  custom_dir: docs
  logo: assets/iclogo.png
  favicon: assets/PARS_logo-01-cropped.svg
  font:
    text: Roboto
    code: Roboto Mono

  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  # SPA behaviour
  features:
    - navigation.instant
    - navigation.top
    - toc.follow
    - content.code.annotate
extra:
  homepage: https://headlabic.github.io/PARS

# Add here all the plugins you want to use.
# Don't forget to add them in requirements.txt as well.
plugins:
  - tags
  - search
  - include-markdown # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - mkdocs-jupyter
  - exclude:
      glob:
      - "LICENSE.md"

# Set settings for markdown extensions
markdown_extensions:
  - meta
  - mdx_math:
      enable_dollar_delimiter: True
  - pymdownx.highlight:
      anchor_linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition # for note box
  - pymdownx.details # for note box
  - attr_list # for figure caption
  - md_in_html # for figure caption
  - pymdownx.blocks.caption # for figure caption

# Render math in mkdocs
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
