site_name: PARS - HEAD Lab
repo_url: https://github.com/HEADLabIC/PARS.git
edit_uri: tree/main/docs/

nav:
  - Home: index.md
  - Installation: installation.md
  - Run in Codespaces: codespaces.md
  - Using PARS: usage.md
  - Outputs: outputs.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material
  custom_dir: docs
  logo: assets/HeadLab-Logo-white.png
  favicon: assets/PARS_logo-01-cropped.svg
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - toc.follow
    - content.code.copy

plugins:
  - search
  - include-markdown
  - mkdocs-jupyter
  - exclude:
      glob:
        - "LICENSE.md"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
